LionsTruck/force-app/main/default/objects/L_ServiceInteraction__c/L_ServiceInteraction__c.object-meta.xml
<CustomObject>
    <description>To Track Truck Service Interactions by Client</description>
    <label>Service Interaction</label>
    <nameField>
        <label>Service Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LionsTruck/force-app/main/default/objects/L_ServiceInteraction__c/fields/L_Asset__c.field-meta.xml
<CustomField>
    <fullName>L_Asset__c</fullName>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.L_AccountId__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Service Interactions</relationshipLabel>
    <relationshipName>Service_Interactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LionsTruck/force-app/main/default/classes/L_ServiceInteraction_TL.cls
public class L_ServiceInteraction_TL {
    
    /*************************************************************************************************
    * @Author:      Stuart Martinho
    * @Date:       07/05/2021
    * @Description: To update Asset fields whenever a new Service Interaction is createdS
    **************************************************************************************************/
    public static void updateAssetDetails(List<L_ServiceInteraction__c> serviceInteractionList){
        
        Set<Id> assetIDs = getAssetsIds(serviceInteractionList);
        List<Asset> assetsToUpdate = new List<Asset>();
        List<Asset> assetsFromServices = L_QueryHandler.getAssetsWithVINByIds(assetIDs);
        sObject sObjAsset;
        
        for(Asset assetObj : assetsFromServices){
            L_Integration_TL.updateAssetInformation(assetObj.id, L_Constants.INT_ENDPOINTURL_VALUE,  L_Constants.HTTP_METHOD_GET, 120000, L_Constants.INT_CLIENTID_APINAME, L_Constants.INT_CLIENTSECRET_VALUE, assetObj.SerialNumber);
        }
        
        update assetsToUpdate;
    }
    
    /*************************************************************************************************
    * @Author:      Stuart Martinho
    * @Date:       07/05/2021
    * @Description: get Asset Ids from ServiceInteraction List
    **************************************************************************************************/
    private static Set<Id> getAssetsIds(List<L_ServiceInteraction__c> serviceInteractionList){
        Set<Id> assetIds = new Set<Id>();
        
        for(L_ServiceInteraction__c serviceIObj : serviceInteractionList){
            assetIds.add(serviceIObj.L_Asset__c);
        }
        
        return assetIds;
    } 

}