LionsTruck/force-app/main/default/objects/Opportunity/fields/L_ServicesAmount__c.field-meta.xml
<CustomField>
    <fullName>L_ServicesAmount__c</fullName>
    <description>To store services amount value</description>
    <label>Services Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

LionsTruck/force-app/main/default/objects/Opportunity/fields/L_ServicesQuantity__c.field-meta.xml
<CustomField>
    <fullName>L_ServicesQuantity__c</fullName>
    <description>Purchased services</description>
    <label>Services Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LionsTruck/force-app/main/default/objects/Opportunity/fields/L_TrucksQuantity__c.field-meta.xml
<CustomField>
    <fullName>L_TrucksQuantity__c</fullName>
    <description>Trucks quantity based on the products added</description>
    <label>Trucks Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LionsTruck/force-app/main/default/objects/OpportunityLineItem/fields/L_AddedService__c.field-meta.xml
<CustomField>
    <fullName>L_AddedService__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To track if the client wants the service</description>
    <label>Add Service</label>
    <type>Checkbox</type>
</CustomField>

LionsTruck/force-app/main/default/classes/L_OpportunityLineItem_TL.cls
public without sharing class L_OpportunityLineItem_TL {
    
    /*************************************************************************************************
    * @Author:      Stuart Martinho
    * @Date:       07/05/2021
    * @Description: This method is used to recalculate the Opportunity Parent quantities and values,
     whenever a new Opportunity LI is created/updated.
    **************************************************************************************************/
    public static void calculateOpportunityParentCounters(List<OpportunityLineItem> oppLIlist) {
        
        Set<Id> parentOppIDs = getOpportunityParentIds(oppLIlist);
		Map<Id, Opportunity> opportunitiesMap = L_QueryHandler.getOpportunitiesMapById(parentOppIDs);
        Map<Id, List<OpportunityLineItem>> oppLIPerOpportunityIdMap = L_QueryHandler.getOppLIPerOpportunityParentId(parentOppIDs);
        
        Decimal trucksCounter = 0;
        Decimal servicesCounter = 0;
        Decimal servicesValue = 0;
        
        for(Id oppId : oppLIPerOpportunityIdMap.keySet()){
            trucksCounter = 0;
        	servicesCounter = 0;
            for(OpportunityLineItem oppLIObj : oppLIPerOpportunityIdMap.get(oppId)){
                trucksCounter += oppLIObj.Quantity;
                if(oppLIObj.L_AddedService__c){
                   servicesCounter += oppLIObj.Quantity;
                   servicesValue += oppLIObj.TotalPrice;
                }
            }
            
            opportunitiesMap.get(oppId).L_TrucksQuantity__c = trucksCounter;
            opportunitiesMap.get(oppId).L_ServicesQuantity__c = servicesCounter;
            opportunitiesMap.get(oppId).L_ServicesAmount__c = servicesValue * L_Constants.TRUCK_SERVICE_PERCENTAGE;
        }
        
        update opportunitiesMap.values();        
    }
    
    /*************************************************************************************************
    * @Author:      Stuart Martinho
    * @Date:       07/05/2021
    * @Description: To get OpportunityIds Set from the given opportunities LI list.
    **************************************************************************************************/
    private static Set<Id> getOpportunityParentIds(List<OpportunityLineItem> oppLIlist) {
        
        Set<Id> oppSetIds = new Set<Id>();
        
        for(OpportunityLineItem oppLIObj : oppLIlist){
            oppSetIds.add(oppLIObj.OpportunityId);
        }
        
        return oppSetIds;
    }
    
}