LionsTruck/force-app/main/default/objects/Asset/fields/L_InitialService__c.field-meta.xml
<CustomField>
    <fullName>L_InitialService__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To track if this Truck was purchased with service included</description>
    <label>Initial Service</label>
    <type>Checkbox</type>
</CustomField>

LionsTruck/force-app/main/default/objects/Asset/fields/L_PS__c.field-meta.xml
<CustomField>
    <fullName>L_PS__c</fullName>
    <description>PS truck value</description>
    <inlineHelpText>Truck Horse Power</inlineHelpText>
    <label>PS</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LionsTruck/force-app/main/default/objects/Asset/fields/L_Tonnage__c.field-meta.xml
<CustomField>
    <fullName>L_Tonnage__c</fullName>
    <description>Truck Tonnage value</description>
    <label>Tonnage</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LionsTruck/force-app/main/default/objects/OpportunityLineItem/fields/L_AddedService__c.field-meta.xml
<CustomField>
    <fullName>L_AddedService__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To track if the client wants the service</description>
    <label>Add Service</label>
    <type>Checkbox</type>
</CustomField>

LionsTruck/force-app/main/default/objects/Product2/fields/L_PS__c.field-meta.xml
<CustomField>
    <fullName>L_PS__c</fullName>
    <description>Field to store the horse power of the truck</description>
    <inlineHelpText>Horse Power</inlineHelpText>
    <label>PS</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LionsTruck/force-app/main/default/objects/Product2/fields/L_Tonnage__c.field-meta.xml
<CustomField>
    <fullName>L_Tonnage__c</fullName>
    <description>Tonnage value of the Truck</description>
    <label>Tonnage</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LionsTruck/force-app/main/default/classes/L_Opportunity_TL.cls
public without sharing class L_Opportunity_TL {


    /*************************************************************************************************
    * @Author:      Stuart Martinho
    * @Date:       07/05/2021
    * @Description: This method is used create a new Assets whenever a Opportuny is set as Closed Won
    **************************************************************************************************/
    public static void processClosedWonOpportunities(Map<Id, Opportunity> oppMap){
        
        if(oppMap.IsEmpty()){
            return;
        }
        
        List<Asset> assetsToCreate = new List<Asset>();
        List<OpportunityLineItem> oppLIsList = L_QueryHandler.getOppLIByOppIdList(oppMap.keyset());
        
        for(OpportunityLineItem oppLIObj : oppLIsList){
            createAsset(oppLIObj, assetsToCreate);
        }    
        
        insert assetsToCreate;
    }
    
    /*************************************************************************************************
    * @Author:      Stuart Martinho
    * @Date:       07/05/2021
    * @Description: This method is used to populate an Asset list, depending on the provided Opportinity Li obj data
    **************************************************************************************************/
    private static void createAsset(OpportunityLineItem oppLIObj, List<Asset> assetsToCreate){        
        for (Integer i = 0; i < oppLIObj.Quantity; i++) {
            assetsToCreate.add(new Asset(Name=oppLIObj.Product2.Name, AccountId=oppLIObj.Opportunity.AccountId, Product2Id=oppLIObj.Product2Id,
                                         L_PS__c=oppLIObj.Product2.L_PS__c, L_Tonnage__c=oppLIObj.Product2.L_Tonnage__c, PurchaseDate=System.Today(),
                                         L_InitialService__c=oppLIObj.L_AddedService__c, SerialNumber=L_GuidUtility.newGuid()));
        }
    }
    
    /*************************************************************************************************
    * @Author:      Stuart Martinho
    * @Date:       07/05/2021
    * @Description: To filter only the opportunities that were set to Close Won status
    **************************************************************************************************/
    public static Map<Id, Opportunity> filterClosedWonOpps(Map<Id, Opportunity> oldOppMap, Map<Id, Opportunity> newOppMap){
        Map<Id, Opportunity> mapToReturn = new Map<Id, Opportunity>();
        for(Opportunity oppObj : newOppMap.values()){
            
            if(oldOppMap.get(oppObj.id).StageName != oppObj.StageName && oppObj.StageName.equalsIgnoreCase(L_Constants.OPP_CLOSED_STATUS)){
                mapToReturn.put(oppObj.id, oppObj);
            }
        }
        
        return mapToReturn;
    }
}